import { SORT_ASC } from '../constants';

const columns = [
  { id: 'id', label: 'Id', width: 70, align: 'left', isSorted: false, order: SORT_ASC, queue: 1 },
  { id: 'firstName', label: 'First name', width: 130, align: 'left', isSorted: false, order: SORT_ASC, queue: 1 },
  {
    id: 'lastName',
    label: 'Last name',
    width: 150,
    align: 'left',
    isSorted: false,
    order: SORT_ASC,
    queue: 1,
    isShift: false,
  },
  {
    id: 'address',
    label: 'Address',
    width: 150,
    align: 'left',
    isSorted: false,
    order: SORT_ASC,
    queue: 1,
    isShift: false,
  },
  {
    id: 'ageCategory',
    label: 'Age',
    width: 90,
    align: 'left',
    isSorted: false,
    order: SORT_ASC,
    queue: 1,
    isShift: false,
  },
  {
    id: 'salary',
    label: 'Salary',
    width: 150,
    align: 'left',
    // format: value => value.toLocaleString(),
    isSorted: false,
    order: SORT_ASC,
    queue: 1,
    isShift: false,
  },
  {
    id: 'distance',
    label: 'Distance',
    width: 150,
    align: 'left',
    format: '5',
    isSorted: false,
    order: SORT_ASC,
    queue: 1,
    isShift: false,
  },
  {
    id: 'hackedDate',
    label: 'Hacked date',
    width: 150,
    align: 'center',
    isSorted: false,
    order: SORT_ASC,
    queue: 1,
    isShift: false,
  },
  {
    id: 'status',
    label: 'Status',
    disablePadding: true,
    width: 100,
    align: 'center',
    isSorted: false,
    order: SORT_ASC,
    queue: 1,
    isShift: false,
  },
];

export default columns;
